export const GET_APPSTATE = 'GET_APPSTATE';
export const GET_APPSTATE_SUCCESS = 'GET_APPSTATE_SUCCESS';
export const GET_APPSTATE_FAILED = 'GET_APPSTATE_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const UPDATE_APPSTATE = 'UPDATE_APPSTATE';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
export const UPDATE_ACTIVE_CATEGORY = 'UPDATE_ACTIVE_CATEGORY';

export const GET_CATEGORY_WORDS = 'GET_CATEGORY_WORDS';
export const GET_CATEGORY_WORDS_SUCCESS = 'GET_CATEGORY_WORDS_SUCCESS';
export const GET_CATEGORY_WORDS_FAILED = 'GET_CATEGORY_WORDS_FAILED';

export const UPDATE_QUIZ_STATE = 'UPDATE_QUIZ_STATE';